#!/usr/bin/env python3
# Generate site/js/dims.js — the per-image aspect ratios used by the gallery to
# compute the justified grid *before* any pixel loads (no reflow on appearance).
#
# Ratios are a pure function of the kept JPEG originals in downloads/, so this
# file is regenerated wholesale from disk; there's no incremental bookkeeping.
# PIL reads dimensions from the header without decoding pixels, so it's cheap.
#
# Usage: python3 tools/gen-dims.py            (scans site/assets/{album,series}/)

import os
import re
import sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, 'site', 'assets')
OUT = os.path.join(ROOT, 'site', 'js', 'dims.js')

NN_RE = re.compile(r'_(\d+)\.[^.]+$')


def img_order(name):
    m = NN_RE.search(name)
    return int(m.group(1)) if m else 0


def ratio_of(path):
    # Header-only read (no pixel decode); honor EXIF orientation so a rotated
    # image gets the ratio it is actually displayed at.
    with Image.open(path) as im:
        w, h = im.size
        orientation = im.getexif().get(0x0112, 1)  # 0x0112 = Orientation
    if orientation in (5, 6, 7, 8):  # 90°/270° → axes swapped
        w, h = h, w
    return round(w / h, 4) if h else 1


def collect(kind):
    root = os.path.join(ASSETS, kind)
    out = {}
    if not os.path.isdir(root):
        return out
    for slug in sorted(os.listdir(root)):
        downloads = os.path.join(root, slug, 'downloads')
        if not os.path.isdir(downloads):
            continue
        files = [f for f in os.listdir(downloads)
                 if f.lower().endswith(('.jpg', '.jpeg', '.png'))
                 and os.path.isfile(os.path.join(downloads, f))]
        files.sort(key=img_order)
        ratios = []
        for f in files:
            try:
                ratios.append(ratio_of(os.path.join(downloads, f)))
            except Exception as e:
                # One unreadable file must not abort the whole run; keep the index
                # aligned with a square fallback and warn.
                print(f"  ⚠ gen-dims: cannot read {kind}/{slug}/{f} ({e}); using 1.0",
                      file=sys.stderr)
                ratios.append(1.0)
        if ratios:
            out[slug] = ratios
    return out


def render(data):
    lines = ['// Machine-generated by tools/gen-dims.py — do not edit by hand.',
             '// Per-image aspect ratios (width / height), indexed 1→count, used to',
             '// lay out the justified grid before the images themselves load.',
             'const VFE_DIMS = {']
    kinds = list(data.keys())
    for ki, kind in enumerate(kinds):
        items = data[kind]
        if not items:
            lines.append(f'  {kind}: {{}}{"," if ki < len(kinds) - 1 else ""}')
            continue
        lines.append(f'  {kind}: {{')
        slugs = list(items.keys())
        for si, slug in enumerate(slugs):
            arr = ', '.join(repr(r) for r in items[slug])
            comma = ',' if si < len(slugs) - 1 else ''
            lines.append(f'    {slug}: [{arr}]{comma}')
        lines.append(f'  }}{"," if ki < len(kinds) - 1 else ""}')
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main():
    data = {'album': collect('album'), 'series': collect('series')}
    with open(OUT, 'w') as f:
        f.write(render(data))
    total = sum(len(v) for d in data.values() for v in d.values())
    print(f"dims.js written: {total} image ratio(s) across "
          f"{len(data['album'])} album(s) + {len(data['series'])} series.")


if __name__ == '__main__':
    main()
